<?php
/** @var  $block View */

/** @var $escaper Escaper */

use Magento\Framework\Escaper;
use PeachCode\RentalSystem\Block\Cart\View;
?>
<?php if($block->isActive()):?>
<div class="minicart-rent">
    <a class="rent-link"
       href="<?= $escaper->escapeUrl($block->getViewUrl());?>">
        <?= $escaper->escapeUrl(__('Rent Cart'));?>
    </a>
    <p class="rent-count"><?= $escaper->escapeHtml($block->getRentItemsCount())?></p>
</div>
<?php endif;?>
