<?php

 /** @var $block Info */
/** @var $escaper Escaper */

use PeachCode\RentalSystem\Block\Orders\Info;
use Magento\Framework\Escaper;

$_order = $block->getOrder() ?>
<div class="table-wrapper order-items">
    <table class="data table table-order-items" id="my-orders-table" summary="<?= $escaper->escapeHtml(__('Items Ordered'));?>">
        <caption class="table-caption"><?= $escaper->escapeHtml(__('Rent Ordered'));?></caption>
        <thead>
            <tr>
                <th class="col name"><?= $escaper->escapeHtml(__('Product Name'));?></th>
                <th class="col sku"><?= $escaper->escapeHtml(__('SKU'));?></th>
                <th class="col qty"><?= $escaper->escapeHtml(__('Qty'));?></th>
                <th class="col price"><?= $escaper->escapeHtml(__('Product Price'));?></th>
                <th class="col days"><?= $escaper->escapeHtml(__('Days'));?></th>
                <th class="col discount"><?= $escaper->escapeHtml(__('Discount'));?></th>
                <th class="col full-price"><?= $escaper->escapeHtml(__('Price'));?></th>
            </tr>
        </thead>
        <?php
        $_items = $_order->getAllItems();
        $_index = 0;
        $_count = $_items->count();
        foreach ($_items as $_item):
                $startDate = new DateTime($_item->getStartDate());
                $endDate = new DateTime($_item->getEndDate());
                $interval = $startDate->diff($endDate);
                $elapsed = $interval->format('%a');
            ?>
        <br>
            <tbody>
                    <tr>
                        <td class="col name"><?= $escaper->escapeHtml($_item->getName()) ?></td>
                        <td class="col sku"><?= $escaper->escapeHtml($_item->getSku()) ?></td>
                        <td class="col qty"><?= $escaper->escapeHtml(1); ?></td>
                        <td class="col price"><?= $block->convertValue($_item->getPrice()); ?></td>
                        <td class="col days"><?= $escaper->escapeHtml(__('%1 days',$elapsed)); ?></td>
                        <td class="col days"><?= $escaper->escapeHtml(__('%1 %',$_item->getDiscount())); ?></td>
                        <td class="col full-price"><?= $block->convertValue($_item->getFullDays() * $_item->getPrice()); ?></td>
                    </tr>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
